### ISSUE TITLE
Missing API-Key

### ISSUE THREAD

**Issue by crotondo-dap** [Inedo/pgscan#18]
Hi,

the method RecordPackageDependenciesInternalAsync() in ProGetClient.cs does not add the ApiKey to the request headers.
This leads to the following server response, even if an ApiKey is given:
![image](https://user-images.githubusercontent.com/102721558/177489416-36909fee-f5d7-4ebc-92a0-932ec542927d.png)

Can you confirm this behavior?

**Comment by gdivis** [comment]
Yes, that's definitely a bug. We'll get v1.3.1 deployed with this fixed as soon as possible.

Thanks!
