### ISSUE TITLE
Support build output paths (other than the default one)

### ISSUE THREAD

**Issue by eschbachJR** [Inedo/pgscan#20]
Hi,
as discussed after submitting a support ticket pgscan supports that the build output of Visual Studio (project.assets.json) is in the directory of the .csproj. For example .\MyProject\obj\project.assets.json. 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/113026580/188866613-8ca88a0a-524e-44c9-a523-fc2c740abf16.png)

We have configured other output paths for our Visual Studio projects for example:  .\Output\obj\MyProject\project.assets.json so pgscan doesn't find any packages

It would be awesome if pgscan would search recursively in the directory of the .sln for all project.assets.json and read the project name (here: MyProject) from the project.assets.json. Then it would find the files even if they are in a completely different output path.

If not possible it would help to at least specify a custom path / fallback path where it searches for the project.assets.json in case it wasn't found in the default path.

**Comment by gdivis** [comment]
Hi @eschbachJR,

We've updated pgscan to search recursively from the solution directory for all `project.assets.json` files. It took a few more changes than expected so we bumped the minor version up to 1.4.0, and aren't ready to publish a stable version just yet.

Would you be willing to test a prerelease build with your configuration? If you're using this as a dotnet tool, you can install v1.4.0-ci.1 by first adding https://proget.inedo.com/nuget/NuGetLibraries/v3/index.json as a nuget package source.

Or, if you'd prefer to just download it as a zip file, you can get it from the Build Artifacts section of [this page](https://buildmaster.inedo.com/applications/78/builds/build?buildId=10122) (use either zip file - one requires .net 4.6.2 and the other requires .net 6.0).

Thanks!
-Greg

**Comment by eschbachJR** [comment]
Hi @gdivis,
I appreciate your super fast implementation. I tested it with our project and it worked perfectly fine! The SBOM was generated as expected. When can we expect a stable version? Just as a rough idea for our schedule.

Thank you so much.
Jana

**Comment by gdivis** [comment]
Hi @eschbachJR,

We'll release it early next week. Probably Tuesday or Wednesday - now that you've tested it with your data and we've tested it for regressions it shouldn't be a problem.

-Greg
