### ISSUE TITLE
.Net 7 runtime support

### ISSUE THREAD

**Issue by mortenf1984** [Inedo/pgscan#40]
Hi! Is it possible to get support to run PGScan in a .Net7 SDK? If I run the commands inside Dockerfile in a .net6 project, it works as expected, but if I try to run it on a .net 7 project, it fails, and will not work, as it expects .Net6 installed, and I am unable to run both .Net6 and .Net7 inside the SDK container

See error message:
##[error]#19 [build 11/15] RUN dotnet tool run pgscan identify --type=nuget --input=***.csproj --project-name=*** --version=*** --project-type=application --proget-url=*** --***-key=***
##[error]#19 0.656 You must install or update .NET to run this application.
##[error]#19 0.656 
##[error]#19 0.656 App: /root/.nuget/packages/pgscan/1.5.4/tools/net6.0/any/pgscan.dll
##[error]#19 0.657 Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
##[error]#19 0.657 .NET location: /usr/share/dotnet/
##[error]#19 0.657 
##[error]#19 0.657 The following frameworks were found:
##[error]#19 0.658   7.0.10 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
##[error]#19 0.658 
##[error]#19 0.658 Learn about framework resolution:
##[error]#19 0.658 https://aka.ms/dotnet/app-launch-failed
##[error]#19 0.658 
##[error]#19 0.658 To install missing framework, download:
##[error]#19 0.658 https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=debian.11-x64
##[error]#19 ERROR: process "/bin/sh -c dotnet tool run pgscan identify --type=nuget --input=${PROJECT_FOLDER}${PROJECT_NAME}.csproj --project-name=${PROJECT_NAME} --version=${VERSION} --project-type=application --proget-url=${URL} --***-key=${PROGET_SBOM_APIKEY}" did not complete successfully: exit code: 150
##[error]------

**Comment by gdivis** [comment]
We've just published v1.5.5 which adds .net 7 as a target runtime version for the pgscan tool. Hope this helps!
