### ISSUE TITLE
Take project references into account 

### ISSUE THREAD

**Issue by crotondo-dap** [Inedo/pgscan#7]
The project.assets.json contains references of type 'package' and 'project' for a project. Pgscan only considers references of type 'package'. But if project references are provided as NuGet packages it would be preferable to publish the consumer information to these packages as well.
Especially since project references are being added as package dependencies to the resulting .nupkg if a project gets packed (not matter which pack command is being used - 'dotnet pack' or 'msbuild -t:pack').

Let's take the following solution as an example:
![image](https://user-images.githubusercontent.com/102721558/162925376-6cb96d48-ffff-4500-8fb1-a57fa4dd16d6.png)
The project 'Utilitites' has a package dependency to Newtonsoft.Json and a project dependency to 'Utilities.Core'. 
The resulting project.assets.json of the project 'Utilities' contains the following libraries:
![image](https://user-images.githubusercontent.com/102721558/162925800-53c9ad74-2848-4493-8e6d-37e0c571a8ff.png)
Both dependencies get listed as package dependencies in the metadata of 'Utilitites.nupkg':
![image](https://user-images.githubusercontent.com/102721558/162926007-b12332dd-00eb-4676-9f1d-f533e60f7228.png)
'Utilitites' and 'Utilitites.Core' are both available as NuGet package on my ProGet server. Using 'pgscan report' gives the following output:
![image](https://user-images.githubusercontent.com/102721558/162926887-5021f633-228d-4590-a947-c6c6498a0a46.png)
Therefore, 'pgscan publish' won't add 'Utilities' as consumer to the package 'Utilities.Core'.

The solution I have in mind is to remove the filter for the type ‚package‘ and to take all libraries into consideration.

Maybe you have already considered this scenario and have another solution in mind.

**Comment by gdivis** [comment]
Hi,

What do you think about adding a switch to enable this behavior?

**Comment by crotondo-dap** [comment]
Hi,

thank you for your input.
I have committed a pull request for this issue. Maybe you can have a look at it? Thanks.

**Comment by gdivis** [comment]
Thanks!

We'll take a look and try to get that merged in the next couple days.
